[phases.setup]
nixPkgs = ['php83', 'composer']

[phases.build]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-interaction --no-scripts'
]

[phases.start]
cmds = [
  'php -S 0.0.0.0:80 -t /app'
]

[variables]
COMPOSER_ALLOW_SUPERUSER = '1'
